management:
  endpoints:
    web:
      exposure:
        include: info,health,metrics,prometheus
  metrics:
    tags:
      application: stock-exchange
  prometheus:
    metrics:
      export:
        enabled: true
