springdoc:
  swagger-ui:
    path: /

management:
  prometheus:
    metrics:
      export:
        enabled: false
  wavefront:
    metrics:
      export:
        enabled: false
  endpoints:
    metrics:
      enabled: true
    web:
      exposure:
        include: info,health,metrics
