config:
  exchange-name: aaa
  delay-duration: 10ms
  generator-prefix: A

management:
  wavefront:
    application:
      service-name: exchange-aaa
  metrics:
    tags:
      instance: exchange-aaa

server:
  port: 9091