config:
  exchange-name: bbb
  delay-duration: 100ms
  generator-prefix: B

management:
  wavefront:
    application:
      service-name: exchange-bbb
  metrics:
    tags:
      instance: exchange-bbb

server:
  port: 9092