---
version: "3"
services:

  grafana:
    image: grafana/grafana:10.3.1
    container_name: grafana
    volumes:
      - "./provisioning:/etc/grafana/provisioning"
      - "./grafana.ini:/etc/grafana/grafana.ini"
    ports:
    - "3000:3000"

  prometheus:
    image: prom/prometheus:v2.49.1
    container_name: prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
