global:
  scrape_interval: 5s
  scrape_timeout: 1s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'apps'
    metrics_path: '/actuator/prometheus'
    honor_labels: true
    static_configs:
      - targets: 
        - '127.0.0.1:8080'
        - '127.0.0.1:9091'
        - '127.0.0.1:9092'
